require "test_helper"
require 'mocha/minitest'

class AiChefFlowTest < ActionDispatch::IntegrationTest
  setup do
    @user = users(:john)
    login_as(@user)
    
    # Mock the recipe generator to avoid actual API calls
    @mock_recipe = Recipe.create!(
      user: @user,
      title: "AI Generated Recipe",
      description: "A recipe generated by AI",
      instructions: "Follow these instructions",
      prep_time: 15,
      cook_time: 25,
      status: :pending
    )
  end

  test "ai chef recipe generation flow" do
    # Step 1: Submit ingredients for recipe generation
    GenerateRecipeJob.stubs(:perform_later).returns(true)
    
    post "/api/v1/ai_chef/generate_recipe", params: {
      ingredients: ["chicken", "rice", "broccoli"]
    }
    assert_response :success
    
    initiation_response = JSON.parse(response.body)
    recipe_id = initiation_response["recipeId"]
    assert_not_nil recipe_id

    # Verify recipe exists in DB from the test's perspective immediately after creation
    created_recipe = Recipe.find_by(id: recipe_id)
    assert_not_nil created_recipe, "Recipe with ID #{recipe_id} should exist in the database after POST"
    assert_equal "pending", created_recipe.status, "Recipe should be in pending state after creation"

    # Step 2: Check recipe status while pending
    get "/api/v1/ai_chef/recipe_status/#{recipe_id}"
    assert_response :success
    
    status_response = JSON.parse(response.body)
    assert_equal "pending", status_response["recipe"]["status"]
    
    # Step 3: Simulate recipe completion
    Recipe.find(recipe_id).update(
      status: :completed,
      title: "AI Chicken and Rice",
      description: "A delicious chicken and rice dish",
      instructions: "1. Cook rice\n2. Cook chicken\n3. Add broccoli",
      prep_time: 10,
      cook_time: 20,
      ingredient_entries: ["2 chicken breasts", "1 cup rice", "1 head broccoli"]
    )
    
    # Step 4: Check recipe status after completion
    get "/api/v1/ai_chef/recipe_status/#{recipe_id}"
    assert_response :success
    
    completion_response = JSON.parse(response.body)
    assert_equal "completed", completion_response["recipe"]["status"]
    assert_equal "AI Chicken and Rice", completion_response["recipe"]["title"]
    
    # Step 5: View the generated recipe
    get "/api/v1/recipes/#{recipe_id}"
    assert_response :success
    
    recipe_response = JSON.parse(response.body)
    assert_equal "AI Chicken and Rice", recipe_response["recipe"]["title"]
    assert_equal 10, recipe_response["recipe"]["prep_time"]
    assert_equal 20, recipe_response["recipe"]["cook_time"]
    
    # Step 6: Simulate recipe generation failure
    another_recipe_id = Recipe.create!(user: @user, title: "Failed Recipe", status: :pending).id
    Recipe.find(another_recipe_id).update(status: :failed)
    
    get "/api/v1/ai_chef/recipe_status/#{another_recipe_id}"
    assert_response :success
    
    failure_response = JSON.parse(response.body)
    assert_equal "failed", failure_response["recipe"]["status"]
  end
end 