source "https://rubygems.org"

# Use dotenv for environment variables
gem 'dotenv'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.0"
# Use postgresql as the database for Active Record
gem "pg", "~> 1.1"
# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ windows jruby ]

# Use the database-backed adapters for Rails.cache and Active Job
gem "solid_cache"
gem "solid_queue"

# Deploy this application anywhere as a Docker container [https://kamal-deploy.org]
gem "kamal", require: false

# Add HTTP asset caching/compression and X-Sendfile acceleration to Puma [https://github.com/basecamp/thruster/]
gem "thruster", require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# Use Panko Serializer for JSON serialization
gem 'panko_serializer', github: 'yosiat/panko_serializer', branch: 'master'

# Use Devise for authentication
gem 'devise'

# Use pg_search for full text search
gem 'pg_search'

# Use Pagy for pagination
gem 'pagy'

# Use Anthropic for AI generation
gem 'anthropic'

# Use Unsplash for image search
gem 'unsplash'

# Use pgvector for vector search
gem 'pgvector'

# Use OpenAI for embeddings
gem 'ruby-openai'

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri windows ], require: "debug/prelude"

  # Static analysis for security vulnerabilities [https://brakemanscanner.org/]
  gem "brakeman", "~> 7.0.2", require: false

  # Omakase Ruby styling [https://github.com/rails/rubocop-rails-omakase/]
  gem "rubocop-rails-omakase", require: false

  # Use Minitest for testing
  gem "minitest"
  gem "mocha"
end


